services:
  scrapper-despesa-gabinete:
    container_name: scrapper-despesa-gabinete
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /apps/despesas-de-gabinete-e-presencas-de-sessoes/blumenau/gastos/2025/spreadsheets_links.txt:/apps/links/despesas.txt:ro
    networks:
      - server_default

networks:
  server_default:
    external: true
