services:
  scrapper-despesa-gabinete:
    container_name: scrapper-despesa-gabinete
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /apps/links/despesas.txt:/apps/links/despesas.txt:ro
    networks:
      - server_default

networks:
  server_default:
    external: true